//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr8_muraEntities1 : DbContext
    {
        public pr8_muraEntities1()
            : base("name=pr8_muraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Delivery_Product> Delivery_Product { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Basket> Product_Basket { get; set; }
        public virtual DbSet<PVZ> PVZ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
